# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'temp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myfcmapp

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

end